In [2]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [4]:
import pandas as pd
data=pd.read_csv('/content/emails.csv')

In [5]:
data.describe()

              spam
count  5728.000000
mean      0.238827
std       0.426404
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [6]:
data.tail(10)

                                                   text  spam
5718  Subject: altos na gas model  kim , i know you ...     0
5719  Subject: power market research  i came across ...     0
5720  Subject: re : visit to houston  fyi  - - - - -...     0
5721  Subject: ees risk management presentations for...     0
5722  Subject: re : vacation  vince :  i just found ...     0
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

In [7]:
list(data)

['text', 'spam']

In [8]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

v = set(stopwords.words("english"))
lm = PorterStemmer()

bag = []

for i in range(5728):
    text = re.sub('[^a-zA-Z]', ' ', data['text'][i])
    text = text.lower()
    text= text.split()

    text = [lm.stem(word) for word in text if word not in v]
    text = ' '.join(text)

    bag.append(text)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000)
X = cv.fit_transform(bag).toarray()
y = data['spam']

In [10]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=0
)


classifier = MultinomialNB()


classifier.fit(X_train, y_train)


y_pred = classifier.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

print("Classification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9808027923211169
Confusion Matrix:
[[869  16]
 [  6 255]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       885
           1       0.94      0.98      0.96       261

    accuracy                           0.98      1146
   macro avg       0.97      0.98      0.97      1146
weighted avg       0.98      0.98      0.98      1146